{
  "hash": "bf0454edde0152b8c3b413e994355013",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Task 5 — 理解波动率\"\n---\n\n# 理论\n\n::: {#67556d6f .cell execution_count=2}\n``` {.python .cell-code}\n# ========== 环境准备 ==========\nimport warnings\nwarnings.filterwarnings('ignore')\n\nimport numpy as np\nimport pandas as pd\nimport matplotlib.pyplot as plt\nimport akshare as ak\nimport yfinance as yf\n\nplt.rcParams['font.sans-serif'] = [              # 跨平台中文字体回退\n    'PingFang SC', 'Microsoft YaHei', 'SimHei',\n    'Noto Sans CJK SC', 'WenQuanYi Micro Hei', 'DejaVu Sans',\n]\nplt.rcParams['axes.unicode_minus'] = False\n\nTRADING_DAYS = 252   # 美股一年大约 252 个交易日\n\n\ndef get_close(data, ticker=None):\n    \"\"\"兼容 yfinance 单标的 / 多标的返回格式\"\"\"\n    close = data['Close']\n    if isinstance(close, pd.DataFrame):\n        return close[ticker] if ticker else close.squeeze()\n    return close\n\nprint('环境就绪 ✓')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n环境就绪 ✓\n```\n:::\n:::\n\n\n# 同样的收益体验不同\n\n直接冲高获得100元，和震荡上行获得100元感受不同。\n\n这里其实还可以参考前景理论：人类是损失厌恶的。\n\n::: {#b9a975cd .cell execution_count=3}\n``` {.python .cell-code}\n# ========== 5.1 两种路径，同一终点 ==========\ndays = ['Day 1', 'Day 2', 'Day 3', 'Day 4', 'Day 5']\nx = np.arange(len(days))\nstock_a = [100, 105, 110, 115, 120]\nstock_b = [100, 80, 130, 70, 120]\n\npath_table = pd.DataFrame({'股票A': stock_a, '股票B': stock_b}, index=days)\nprint('价格路径对照：')\ndisplay(path_table)\n\nfig, ax = plt.subplots(figsize=(8, 4))\nax.plot(x, stock_a, 'o-', color='#007AFF', linewidth=2.5, markersize=9, label='股票 A · 平稳上涨')\nax.plot(x, stock_b, 's-', color='#E82127', linewidth=2.5, markersize=9, label='股票 B · 大起大落')\nax.axhline(120, color='gray', linestyle='--', alpha=0.5, label='终点都是 120')\nax.set_xticks(x)\nax.set_xticklabels(days)\nax.set_ylabel('价格')\nax.set_title('收益相同，路径不同：你更愿意持有哪一只？', fontsize=14)\nax.legend()\nax.grid(True, alpha=0.3)\nplt.tight_layout()\nplt.show()\n\nret_a = stock_a[-1] / stock_a[0] - 1\nret_b = stock_b[-1] / stock_b[0] - 1\nprint(f'股票 A 总涨幅: {ret_a:.0%}')\nprint(f'股票 B 总涨幅: {ret_b:.0%}')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n价格路径对照：\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>股票A</th>\n      <th>股票B</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>Day 1</th>\n      <td>100</td>\n      <td>100</td>\n    </tr>\n    <tr>\n      <th>Day 2</th>\n      <td>105</td>\n      <td>80</td>\n    </tr>\n    <tr>\n      <th>Day 3</th>\n      <td>110</td>\n      <td>130</td>\n    </tr>\n    <tr>\n      <th>Day 4</th>\n      <td>115</td>\n      <td>70</td>\n    </tr>\n    <tr>\n      <th>Day 5</th>\n      <td>120</td>\n      <td>120</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![](task5_files/figure-html/cell-3-output-3.png){width=759 height=374}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n股票 A 总涨幅: 20%\n股票 B 总涨幅: 20%\n```\n:::\n:::\n\n\n# 波动\n\n价格不是直线运动的。\n价格没有办法直接比较，因此我们使用波动率。\n\n::: {#5c65f8e4 .cell execution_count=4}\n``` {.python .cell-code}\n# ========== 5.2 电梯 vs 过山车 ==========\nfig, axes = plt.subplots(1, 2, figsize=(9, 4), sharey=True)\n\naxes[0].plot(x, stock_a, 'o-', color='#007AFF', linewidth=2.5, markersize=8)\naxes[0].set_title('股票 A · 像坐电梯\\n上涨平稳', fontsize=12)\naxes[0].set_xticks(x)\naxes[0].set_xticklabels(days, fontsize=9)\naxes[0].grid(True, alpha=0.3)\n\naxes[1].plot(x, stock_b, 's-', color='#E82127', linewidth=2.5, markersize=8)\npeak = np.maximum.accumulate(stock_b)\naxes[1].fill_between(x, stock_b, peak, alpha=0.35, color='#E82127', label='从高点回落')\naxes[1].set_title('股票 B · 像坐过山车\\n大起大落', fontsize=12)\naxes[1].set_xticks(x)\naxes[1].set_xticklabels(days, fontsize=9)\naxes[1].legend(fontsize=9)\naxes[1].grid(True, alpha=0.3)\n\nfor ax in axes:\n    ax.set_ylabel('价格')\n\nfig.suptitle('市场中的「不稳定程度」不同', fontsize=14, y=1.02)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](task5_files/figure-html/cell-4-output-1.png){width=853 height=396}\n:::\n:::\n\n\n# 收益率\n\n收益率是不同股票，不同时期，可以统一进行比较的指标。\n\n两张图：\n\n累计收益率曲线 —— 看长期方向\n收益率直方图 —— 看日常分布是 集中 还是 分散\n\n::: {#16b83341 .cell execution_count=5}\n``` {.python .cell-code}\n# ========== 5.3 收益率曲线 + 直方图 ==========\nTICKER = \"AAPL\"\nraw = ak.stock_us_daily(symbol=TICKER, adjust=\"qfq\")\nraw[\"date\"] = pd.to_datetime(raw[\"date\"])\nraw = raw.set_index(\"date\").sort_index()\nraw = raw[raw.index >= \"2024-01-01\"]  # 近一年数据\ndf = pd.DataFrame({\"Close\": raw[\"close\"]})\ndf[\"return\"] = df[\"Close\"].pct_change()\ndf = df.dropna().copy()\n\ndf[\"cum_return\"] = (1 + df[\"return\"]).cumprod() - 1\n\nfig, axes = plt.subplots(1, 2, figsize=(9, 4))\n\naxes[0].plot(df.index, df[\"cum_return\"] * 100, color=\"#007AFF\", linewidth=1.5)\naxes[0].axhline(0, color=\"gray\", linestyle=\"--\", linewidth=0.8)\naxes[0].set_title(f\"{TICKER} · 累计收益率曲线\", fontsize=13)\naxes[0].set_ylabel(\"累计收益率 (%)\")\naxes[0].grid(True, alpha=0.3)\n\naxes[1].hist(\n    df[\"return\"] * 100, bins=50, color=\"#007AFF\", alpha=0.75, edgecolor=\"white\"\n)\naxes[1].axvline(0, color=\"black\", linestyle=\"--\", linewidth=0.8)\naxes[1].set_title(f\"{TICKER} · 日收益率直方图\", fontsize=13)\naxes[1].set_xlabel(\"日收益率 (%)\")\naxes[1].set_ylabel(\"天数\")\n\nfig.suptitle(\"用收益率观察波动：直方图越「散」，日常越颠\", fontsize=14, y=1.02)\nfig.autofmt_xdate(rotation=30, ha=\"right\")\nplt.tight_layout()\nplt.show()\n\nprint(f\"样本: {len(df)} 个交易日\")\nprint(f\"累计收益: {df['cum_return'].iloc[-1]:.2%}\")\n```\n\n::: {.cell-output .cell-output-display}\n![](task5_files/figure-html/cell-5-output-1.png){width=854 height=397}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n样本: 636 个交易日\n累计收益: 82.53%\n```\n:::\n:::\n\n\n结果怎么读？\n\n左图 回答：「这一年总体赚还是亏？」\n总体盈利为 82.53%。\n\n右图 回答：「大多数日子的涨跌，集中在哪个区间？」\n大多数日子的涨跌集中在 **-2% ~ +2%** 之间（636 个交易日中有 530 天，占 83.3%）。均值约为 0.11%，标准差约 1.75%，说明大部分时间是小幅波动，偶尔出现大涨大跌。\n\n如果直方图 又宽又胖，说明大涨大跌的日子多 → 通常 波动更大。\n如果直方图 又窄又高，说明涨跌集中在均值附近 → 通常 更平稳。\n\n",
    "supporting": [
      "task5_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}